config/routes.rb
BlockBrowser::Application.routes.draw do

  get 'blocks' => 'blocks#index', as: :blocks
  get 'block/:id' => 'blocks#show', as: :block
  get 'tx/:id' => 'tx#show', as: :tx
  get 'script/:id' => 'scripts#show', as: :script
  get 'script/:script_sig/:pk_script' => 'scripts#show'
  get 'script/:script_sig/:pk_script/:sig_hash' => 'scripts#show'
  get 'script' => 'scripts#show'
  get 'address/:id/unspent' => 'address#unspent', as: :address_unspent
  get 'address/:id' => 'address#show', as: :address

  get 'search/:search' => 'search#search'
  get 'search' => 'search#search', as: :search

  get 'unconfirmed' => 'blocks#unconfirmed', as: :unconfirmed
  get 'scripts/:type' => 'scripts#index', as: :scripts
  get 'p2sh_scripts/:type' => 'scripts#p2sh_index', as: :p2sh_scripts

  get 'relay_tx' => 'relay#relay_tx'
  post 'relay_tx' => 'relay#relay_tx'

  get 'api' => 'api#index', as: :api
  get 'api/block' => 'api#block', as: :block_api
  get 'api/tx' => 'api#tx', as: :tx_api
  get 'api/address' => 'api#address', as: :address_api
  get 'api/relay' => 'api#relay', as: :relay_api
  get 'api/stats' => 'api#stats', as: :stats_api
  get 'api/schema' => 'api#schema', as: :schema_api

  get 'graphs' => 'blocks#graphs', as: :graphs

  get 'about' => 'blocks#about', as: :about
  get 'stats' => 'stats#stats', as: :stats
  get 'source' => 'source#source', as: :source

  if Bitcoin.network_project == :namecoin
    get 'names' => 'names#index', as: :names
    get 'name/heights/*name' => 'names#heights', as: :name_heights
    get 'name/*name' => 'names#show', as: :name
    get 'api/name' => 'api#name', as: :name_api
  end

  root :to => 'blocks#index'

end

app/controllers/blocks_controller.rb
require 'timeout'
require 'method_source'

class BlocksController < ApplicationController

  def index
    @per_page = 20
    STORE.instance_eval { @head = nil }
    height = STORE.height
    height = params[:height].to_i  if params[:height] && params[:height].to_i < height
    height = (@per_page - 1)  if height < @per_page
    @blocks = STORE.db[:blk].filter("height <= ?", height).where(chain: 0).order(:height).limit(@per_page).reverse
    @page_title = "Recent Blocks"
  end

  def show
    @block = STORE.block(params[:id])
    return render_error("Block #{params[:id]} not found.", 404)  unless @block
    @siblings = STORE.db[:blk].where(prev_hash: @block.prev_block_hash.blob)
                .reject {|b| b[:id] == @block.id }
                .map {|b| STORE.wrap_block(b) }
    @page_title = "Block Details"
    respond_with(@block, with_next_block: true, with_nid: true, with_address: true, with_next_in: true)
  end

end

app/views/blocks/_address_tx.html.haml
%table.list
  %tr
    %th Tx
    %th Block
    %th Address
    %th Type
    %th Value
    %th Total

  - @addr_txouts.each do |addr_txout|
    - txout = STORE.wrap_txout(STORE.db[:txout][id: addr_txout[:txout_id]])
    - tx = txout.get_tx
    - blk = STORE.db[:blk_tx].where(tx_id: tx.id).join(:blk, id: :blk_id).first
    - next  unless blk 
    - @addr_data[:tx_in_sz] += 1
    - @addr_data[:btc_in] += txout.value

    %tr{:class => cycle('odd', 'even')}
      %td= link_to(tx.hash, tx_path(tx.hash))
      %td= link_to(blk[:height], block_path(blk[:hash].hth))
      %td
        - STORE.db[:txin].where(tx_id: tx.id).order(:tx_idx).each do |prev_in|
          - txin = STORE.wrap_txin(prev_in)
          - if txin.coinbase?
            generation
          - else
            - prev_out = txin.get_prev_out
            - if prev_out
              = link_to(prev_out.get_address, address_path(prev_out.get_address))
            - else
              unknown
            %br/

        %td.incoming= "->"
        %td.value= format_amount(txout.value)
        %td.value= format_amount(@addr_data[:btc_in] - @addr_data[:btc_out])

    - if next_in = txout.get_next_in
      - tx = next_in.get_tx
      - blk = STORE.db[:blk_tx].where(tx_id: tx.id).join(:blk, id: :blk_id).first
      - next  unless blk 
      - @addr_data[:tx_out_sz] += 1
      - @addr_data[:btc_out] += txout.value

      %tr{:class => cycle('odd', 'even')}
        %td= link_to(tx.hash, tx_path(tx.hash))
        %td= link_to(blk[:height], block_path(blk[:hash].hth))
        %td

          %table.tx_outs{cellpadding: 0, cellspacing: 0}
            - txout.get_next_in.get_tx.out.map do |o|
              %tr
                %td
                  - o.get_addresses.map do |addr|
                    = address_link(addr)
                    %br/
                %td (#{format_amount o.value})
        %td.outgoing= "<-"
        %td.value.outgoing= "- #{format_amount(txout.value)}"
        %td.value= format_amount(@addr_data[:btc_in] - @addr_data[:btc_out])

app/views/blocks/about.html.haml
- @page_title = "About"

%h3 About

%p
  This is a #{link_to "bitcoin", "http://bitcoin.org"} blockchain browser written in ruby
  using the #{link_to "bitcoin-ruby", "http://github.com/lian/bitcoin-ruby"} library.

%p
  It allows you to view the technical details that make up the blockchain, and also
  query them easily via the #{link_to "API", api_path}.

%h3 License

%p
  The code is open source and available at
  = link_to "block_browser", "http://github.com/mhanne/block_browser"
  under the terms of the GNU AGPL license.

%p
  This instance is currently running git commit #{`git rev-parse HEAD`.strip}.
  %br/
  The current code is also available for direct download here: #{link_to "/source", source_path}.

%h3 Support

%p
  Donations motivate me to invest even more time that I don't have into this project ;)
  = link_to BB_CONFIG['donate'], address_path(BB_CONFIG['donate'])

%p
  Also don't hesitate to send me any comments, bug reports, feature requests or other feedback you might have to the info@ address on this domain (webbtc.com).

app/views/blocks/address.html.haml
%table.details
  %tr
    %th Address
    %th= @address
  %tr
    %th Hash160
    %th= @hash160
  %tr
    %th Type
    %td= @type
  %tr
    %th Transactions
    %td
      #{@addr_data[:tx_in_sz] + @addr_data[:tx_out_sz]}
      (#{@addr_data[:tx_in_sz]} in, #{@addr_data[:tx_out_sz]} out)
  %tr
    %th Total BTC In
    %td= format_amount(@addr_data[:btc_in])
  %tr
    %th Total BTC Out
    %td= format_amount(@addr_data[:btc_out])
  %tr
    %th Current Balance
    %th= format_amount(@addr_data[:btc_in] - @addr_data[:btc_out])
  %tr
    %th Formats
    %td= link_to "[json]", "/address/#{@address}.json"

%h3 Transactions

= raw @tx_list

app/views/blocks/block.html.haml
%table.details
  - cache("block/#{@block.hash}/details_1") do
    %tr
      %th Block
      %th= @block.hash
    %tr
      %th Height
      %td
        = @block.height
        - unless @block.chain == 0
          %span{style: "color: red"} (Side Chain)
    - if @siblings.any?
      %tr
        %th Siblings
        %td= @siblings.map {|s| link_to s.hash, block_path(s.hash) }.join("<br/>").html_safe
    %tr
      %th Prev Block
      %td= link_to @block.prev_block_hash.reverse_hth, block_path(@block.prev_block_hash.reverse_hth)
  %tr
    %th Next Block
    - blk = STORE.db[:blk][prev_hash: @block.hash.htb.to_sequel_blob, chain: 0]
    - if blk
      %td= link_to(blk[:hash].hth, block_path(blk[:hash].hth))
    - else
      %td not seen
  - cache("block/#{@block.hash}/details_2") do
    %tr
      %th Merkle Root
      %td= @block.mrkl_root.reverse.unpack("H*")[0]
    %tr
      %th Time
      %td= format_time @block.time
    %tr
      %th Transactions
      %td= number_with_delimiter @block.tx.size
    %tr
      %th Size
      %td= number_to_human_size @block.to_payload.bytesize
    %tr
      %th Total Value
      %td= format_amount(@block.tx.map(&:out).flatten.map(&:value).sum)
    %tr
      %th Formats
      %td
        = link_to "[json]", "/block/#{@block.hash}.json"
        = link_to "[hex]", "/block/#{@block.hash}.hex"
        = link_to "[binary]", "/block/#{@block.hash}.bin"

- cache("block/#{@block.hash}/tx") do
  %h3 Transactions
  %table.list
    %tr
      %th Hash
      %th Inputs
      %th Outputs
      %th Size
      %th Value
    = render :partial => 'tx', :collection => @block.tx

app/views/blocks/error.json.erb
{"error": "<%= @error %>"}

app/views/blocks/mempool_tx.html.haml
%table.details
  %tr
    %th Transaction
    %th= @tx.hash
  %tr
    %th Normalized Hash
    %td= @tx.nhash

  %tr
    %th Mempool ID
    %td#mempool_id= @tx.id

  %tr
    %th First Seen
    %td= format_time(@tx.created_at, :with_seconds)
  %tr
    %th Last Seen
    %td#updated_at= format_time(@tx.updated_at, :with_seconds)
  %tr
    %th Times Seen
    %td#times_seen= @tx.times_seen

  - if @tx.doublespend? || @tx.is_doublespent
    %tr.doublespent
      %th Doublespend
      %td
        - if @tx.doublespends
          = link_to @tx.doublespends.hth, mempool_tx_path(@tx.doublespends.hth)
        - else
          - MEMPOOL.doublespend.where(doublespends: @tx.hash.htb.blob).each do |doublespend|
            = link_to doublespend[:hash].hth, mempool_tx_path(doublespend[:hash].hth)
            %br/

  - if @tx.depends.any?
    %tr.depends
      %th Depends on
      %td
        - @tx.depends.each do |hash|
          = link_to hash, mempool_tx_path(hash)
          %br/

  - if @tx.depending.any?
    %tr.depending
      %th Depending
      %td
        - @tx.depending.each do |hash|
          = link_to hash, mempool_tx_path(hash)
          %br/

  - cache("tx/#{@tx.hash}/details") do
    - if Bitcoin.namecoin?
      %tr
        %th Version
        %td= @tx.ver == 0x7100 ? "Namecoin" : "Bitcoin"
    %tr
      %th Size
      %td= @tx.to_payload.bytesize
    %tr
      %th Inputs
      %td= @tx.in.size
    %tr
      %th Outputs
      %td= @tx.out.size
    - if @tx.in.size == 1 && @tx.in[0].coinbase?
      - input_value = Bitcoin.block_creation_reward(@blk[:depth])
    - else
      - input_value = @tx.in.map.with_index {|i, idx| @prev_outs[idx].value }.sum rescue '?'
    %tr
      %th Input Value
      %td= format_amount(input_value) rescue '?'
    - output_value = @tx.out.map(&:value).sum
    %tr
      %th Output Value
      %td= format_amount(output_value)
    %tr
      %th Fee
      %td= format_amount(input_value - output_value) rescue '?'
    - if @tx.lock_time != 0
      %tr
        %th Lock Time
        %td
          - if @tx.lock_time < 500_000_000
            Block #{@tx.lock_time}
          - else
            #{@tx.lock_time} (#{format_time Time.at(@tx.lock_time)})
    %tr
      %th Priority
      %td= number_with_delimiter @tx.priority
    %tr
      %th Formats
      %td
        = link_to "[json]", "/mempool_tx/#{@tx.hash}.json"
        = link_to "[hex]", "/mempool_tx/#{@tx.hash}.hex"
        = link_to "[binary]", "/mempool_tx/#{@tx.hash}.bin"

%h3 Inputs
%table.list
  %tr
    %th IDX
    %th Type
    %th Previous Output
    %th Value
    %th From Address
    %th Script
    - if display_sequence = @tx.in.map(&:sequence).any? {|s| s.unpack("I")[0] != 0xffffffff }
      %th Sequence
    %th Debug


  - @tx.in.each_with_index do |txin, idx|
    %tr{:class => cycle('odd', 'even')}
      -# - prev_hash = txin.prev_out.reverse.hth
      -# - prev_tx = STORE.get_tx(prev_hash) || @mempool.get(prev_hash)
      -# - prev_out = prev_tx.out[txin.prev_out_index] if prev_tx
      - prev_tx_hash = txin.prev_out.reverse.hth
      - prev_out = @prev_outs[idx]
      - prev_script = prev_out.parsed_script  if prev_out

      - cache("tx/#{@tx.hash}/in/#{idx}/#{!!prev_out}") do
        %td= idx
        - if txin.coinbase?
          %td generation
          %td none
          %td.value= format_amount(Bitcoin.block_creation_reward(@blk[:depth]))
          %td -
          %td= txin.script_sig.unpack("H*")[0]
        - else
          - if prev_out
            %td
              - type = Bitcoin::Script.new(prev_out.pk_script).type
              = link_to(type, "/scripts/#{type}")
              -# - if type == :script_hash
              -#   %br/
              -#   (#{link_to txin.p2sh_type, "/p2sh_scripts/#{txin.p2sh_type}"})
            %td
              - if MEMPOOL.exists?(prev_tx_hash)
                = link_to(truncate(prev_tx_hash, length: 16), mempool_tx_path(prev_tx_hash))
              - else
                = link_to(truncate(prev_tx_hash, length: 16), tx_path(prev_tx_hash))
              = "/ #{txin.prev_out_index}"
            %td.value= format_amount(prev_out.value) rescue "?"
            - if prev_script.get_address
              %td
                - prev_script.get_addresses.each do |address|
                  = address_link(address)
                  %br
            - else
              %td not seen
            %td
              %pre
                = Bitcoin::Script.new(txin.script_sig).to_string.split(" ").join("\n")
            - if display_sequence
              %td= txin.sequence.unpack("I")[0].to_s(16)
            %td
              %form{action: script_path}
                %input{type: :hidden, name: :script_sig, value: txin.parsed_script.to_string}
                %input{type: :hidden, name: :pk_script, value: prev_out.parsed_script.to_string}
                %input{type: :hidden, name: :sig_hash, value: @tx.signature_hash_for_input(idx, prev_out.pk_script).hth}
                %input{type: :submit, value: "Run Script"}
          - else
            %td not seen
            %td{colspan: 5, style: "color: red"} #{txin.prev_out.reverse.hth} / #{txin.prev_out_index}


%h3 Outputs
%table.list
  %tr
    %th IDX
    %th Type
    %th Next Input
    %th Value
    %th To Address
    %th Script
    %th Debug
  - @tx.out.each_with_index do |txout, idx|
    - next_input = STORE.db[:txin][prev_out: @tx.hash.htb.reverse.to_sequel_blob, prev_out_index: idx]
    %tr{:class => cycle('odd', 'even')}
      - cache("tx/#{@tx.hash}/out/#{idx}/#{!!next_input}") do

        - spent_out = MEMPOOL.spent_outs[prev_out: "#{@tx.hash.htb}:#{idx}".blob]
        - tx_data = MEMPOOL.transactions[id: spent_out[:spent_by]] if spent_out
        - next_tx = Bitcoin::Blockchain::Mempool::MempoolTx.new(STORE, MEMPOOL.db, tx_data)  if tx_data
        - next_input = next_tx.in.find {|i| i.prev_out.reverse == @tx.hash.htb && i.prev_out_index == idx }  if next_tx

        - script = Bitcoin::Script.new(txout.pk_script) rescue nil
        %td= idx
        %td
          - type = txout.parsed_script.type
          = link_to(type, "/scripts/#{type}")
          - if type == :script_hash
            -# %br/
            -# - if next_input
            -#   (#{link_to next_in.p2sh_type, "/p2sh_scripts/#{next_input.p2sh_type}"})
            -# - else
            -#   (unspent)
        %td
          - if next_input
            = link_to(truncate(next_tx.hash, :length => 16, :omission => '...'), mempool_tx_path(next_tx.hash))
            = "/ #{next_tx.in.index(next_input)}"
          - else
            not seen

        %td.value= format_amount(txout.value)
        %td
          - case type
          - when :pubkey, :pubkey_hash, :script_hash
            - addr = txout.parsed_script.get_address
            = link_to(addr, address_path(addr))
          - when :multisig
            - addrs = script.get_multisig_addresses
            multisig (#{script.get_signatures_required} of #{script.get_keys_provided}):
            %br/
            - addrs.each do |address|
              - if address
                = link_to(address, address_path(address))
              - else
                %span.error Error decoding address from pubkey
              %br
          - when :op_return
            - if script.get_op_return_data
              Data: #{script.get_op_return_data}
            - else
              (No data)
          - if Bitcoin.namecoin? && script.is_namecoin?
            - name = txout.get_namecoin_name
            - if name.name
              #{link_to(name.name, name_path(name.name))}: #{name.value || name.hash}
            - else
              Hash: #{name.hash}
            %br
            - addr = txout.get_address
            = link_to(addr, address_path(addr))
          - if script.type == :unknown
            %span{class: "error"} Unknown script type
        %td
          %pre= script.to_string rescue "?"
        %td
          - if next_input
            -# TODO!
            = link_to "Run Script", script_path("#{next_tx.hash}:#{next_tx.in.index(next_input)}")

:javascript
  ws.add_handler(new MempoolTx(#{@tx.id}, "#{@tx.hash}"));

app/views/blocks/name.html.haml
%table.details
  %tr
    %th Name
    %th= @name
  %tr
    %th Value
    %td
      %pre= @current.value
  %tr
    %th Owner
    %td
      - addr = @current.get_address
      = link_to addr, address_path(addr)
  %tr
    %th Expires In
    %td #{@current.expires_in} blocks
  %tr
    %th Operations
    %td= @names.count
  %tr
    %th Formats
    %td
      = link_to "[json]", "/name/#{@name}.json"
      = link_to "[json history]", "/name/#{@name}.json?history=true"

%h3 History

%table.list
  %tr
    %th Block
    %th Tx
    %th Type
    %th Hash / Value
    %th Address

  - @names.reverse.each do |name|
    %tr{:class => cycle('odd', 'even')}
      %td= link_to(name.block.height, block_path(name.block.hash))  if name.block
      %td= link_to(truncate(name.tx.hash, :length => 16), tx_path(name.tx.hash))
      %td= name.txout.type
      %td
        %pre= name.txout.type == :name_new ? name.hash : name.value
      - addr = name.address
      %td= link_to addr, address_path(addr)

app/views/blocks/names.html.haml
%table#names.list
  %tr
    %th Block
    %th Tx
    %th Type
    %th Name / Hash
  %tbody.blocks
    - @names.each do |name|
      %tr{:class => cycle('odd', 'even')}
        %td= link_to(name.get_block.height, block_path(name.get_block.hash))  if name.get_block
        %td= link_to(truncate(name.get_tx.hash, :length => 16), tx_path(name.get_tx.hash))
        %td= name.get_txout.type
        %td
          - if name.name
            = link_to(name.name, name_path(name.name))
          - else
            = name.hash

- if @page > 1
  = link_to "<<", names_path(:page => @page - 1), :style => "float: left"

- if @offset + @per_page < @max
  = link_to ">>", names_path(:page => @page + 1), :style => "float: right"

app/views/blocks/scripts.html.haml
- @page_title = "#{params[:type]} Scripts"

%p Showing <b>#{params[:type]}</b> scripts #{@offset}-#{@offset + @limit} of #{@count}.

%table.details
  %tr
    %th Block
    %th Transaction
    %th Value
    %th Script
    %th Address(es) / Data
  - @txouts.each do |txout|
    - tx = STORE.db[:tx][id: txout[:tx_id]]
    - blk_tx = STORE.db[:blk_tx][tx_id: txout[:tx_id]]
    - blk = STORE.db[:blk][id: blk_tx[:blk_id]]
    - script = Bitcoin::Script.new(txout[:pk_script])
    %tr
      %td= link_to "#{blk[:height]}", block_path(blk[:hash].hth)
      %td
        = link_to truncate(tx[:hash].hth, :length => 16), tx_path(tx[:hash].hth)
        = "/ #{txout[:tx_idx]}"
      %td= format_amount txout[:value]
      %td
        %pre= script.to_string.gsub("\s", "\n")
      %td
        - if script.is_op_return?
          %pre= script.get_op_return_data
        - else
          - script.get_addresses.each do |addr|
            = address_link(addr)
            %br/
      - if next_in = STORE.db[:txin][prev_out: tx[:hash].reverse.blob, prev_out_index: txout[:tx_idx]]
        - next_tx = STORE.db[:tx][id: next_in[:tx_id]]
        %td= link_to "Run Script", "/script/#{next_tx[:hash].hth}:#{next_in[:tx_idx]}"

- if @offset >= @limit
  = link_to "<<", "?offset=#{@offset - @limit}"

- if @count > @offset + @limit
  = link_to ">>", "?offset=#{@offset + @limit}", style: "float: right"


- stats = JSON.load(File.read(File.join(Rails.root, "public/stats.json")))

%p
  Script Types:
  - STORE.class::SCRIPT_TYPES.each do |type|
    = link_to "#{type} (#{stats['script_types'][type.to_s]})", "/scripts/#{type}"

app/views/blocks/tx.html.haml
%table.details
  %tr
    %th Transaction
    %th= @tx.hash
  %tr
    %th Normalized Hash
    %td= @tx.nhash
  %tr
    %th Block
    %td
      - if @blk
        = link_to(@blk[:hash].hth, block_path(@blk[:hash].hth))
      - else
        unconfirmed
  %tr
    %th Confirmations
    %td
      - if @blk
        = STORE.height - @blk[:height] + 1
        (At Height: #{@blk[:height]})
        - unless @blk[:chain] == 0
          %span{style: "color:red"} (#{["Main", "Side", "Orphan"][@blk[:chain]]} Chain!)
      - else
        unconfirmed

  - cache("tx/#{@tx.hash}/details") do
    - if Bitcoin.namecoin?
      %tr
        %th Version
        %td= @tx.ver == 0x7100 ? "Namecoin" : "Bitcoin"
    %tr
      %th Size
      %td= @tx.to_payload.bytesize
    %tr
      %th Inputs
      %td= @tx.in.size
    %tr
      %th Outputs
      %td= @tx.out.size
    - if @tx.in.size == 1 && @tx.in[0].coinbase?
      - input_value = Bitcoin.block_creation_reward(@blk[:height])
    - else
      - input_value = @tx.in.map(&:get_prev_out).map(&:value).sum rescue '?'
    %tr
      %th Input Value
      %td= format_amount(input_value) rescue '?'
    - output_value = @tx.out.map(&:value).sum
    %tr
      %th Output Value
      %td= format_amount(output_value)
    %tr
      %th Fee
      %td= format_amount(input_value - output_value) rescue '?'
    - if @tx.lock_time != 0
      %tr
        %th Lock Time
        %td
          - if @tx.lock_time < 500_000_000
            - block = STORE.db[:blk][height: @tx.lock_time, chain: 0][:hash].hth
            Block #{link_to @tx.lock_time, "/block/#{block}"}
          - else
            #{@tx.lock_time} (#{format_time @tx.lock_time})
    %tr
      %th Formats
      %td
        = link_to "[json]", "/tx/#{@tx.hash}.json"
        = link_to "[hex]", "/tx/#{@tx.hash}.hex"
        = link_to "[binary]", "/tx/#{@tx.hash}.bin"

%h3 Inputs
%table.list
  %tr
    %th IDX
    %th Type
    %th Previous Output
    %th Value
    %th From Address
    %th Script
    - if display_sequence = @tx.in.map(&:sequence).any? {|s| s.unpack("I")[0] != 0xffffffff }
      %th Sequence
    %th Debug


  - @tx.in.each_with_index do |txin, idx|
    %tr{:class => cycle('odd', 'even')}
      - prev_out = txin.get_prev_out
      - cache("tx/#{@tx.hash}/in/#{idx}/#{!!prev_out}") do
        %td= idx
        - if txin.coinbase?
          %td generation
          %td none
          %td.value= format_amount(Bitcoin.block_creation_reward(@blk[:height]))
          %td -
          %td= txin.script_sig.unpack("H*")[0]
        - else
          - if prev_out
            %td
              = link_to(prev_out.type, "/scripts/#{prev_out.type}")
              - if prev_out.type == :script_hash
                %br/
                (#{link_to txin.p2sh_type, "/p2sh_scripts/#{txin.p2sh_type}"})
            %td
              = link_to(truncate(prev_out.get_tx.hash, :length => 16), tx_path(prev_out.get_tx.hash))
              = "/ #{txin.prev_out_index}"
            %td.value= format_amount(prev_out.value) rescue "?"
            - if prev_out.get_address
              %td
                - prev_out.get_addresses.each do |address|
                  = address_link(address)
                  %br
            - else
              %td not seen
            %td
              %pre
                = Bitcoin::Script.new(txin.script_sig).to_string.split(" ").join("\n")
            - if display_sequence
              %td= txin.sequence.unpack("I")[0].to_s(16)
            %td= link_to "Run Script", script_path("#{@tx.hash}:#{idx}")
          - else
            %td{:colspan => 5} not seen

%h3 Outputs
%table.list
  %tr
    %th IDX
    %th Type
    %th Next Input
    %th Value
    %th To Address
    %th Script
    %th Debug
  - @tx.out.each_with_index do |txout, idx|
    - next_input = STORE.db[:txin][prev_out: @tx.hash.htb.reverse.to_sequel_blob, prev_out_index: idx]
    %tr{:class => cycle('odd', 'even')}
      - cache("tx/#{@tx.hash}/out/#{idx}/#{!!next_input}") do
        - next_input = STORE.wrap_txin(next_input)
        - script = Bitcoin::Script.new(txout.pk_script) rescue nil
        %td= idx
        %td
          = link_to(txout.type, "/scripts/#{txout.type}")
          - if txout.type == :script_hash
            %br/
            - if next_in = txout.get_next_in
              (#{link_to next_in.p2sh_type, "/p2sh_scripts/#{next_input.p2sh_type}"})
            - else
              (unspent)
        %td
          - if next_input
            - tx_hash = next_input.get_tx.hash
            = link_to(truncate(tx_hash, :length => 16, :omission => '...'), tx_path(tx_hash))
            = "/ #{next_input.tx_idx}"
          - else
            not seen

        %td.value= format_amount(txout.value)
        %td
          - case script.type
          - when :pubkey, :pubkey_hash, :script_hash
            - addr = txout.get_address
            = link_to(addr, address_path(addr))
          - when :multisig
            - addrs = script.get_multisig_addresses
            multisig (#{script.get_signatures_required} of #{script.get_keys_provided}):
            %br/
            - addrs.each do |address|
              - if address
                = link_to(address, address_path(address))
              - else
                %span.error Error decoding address from pubkey
              %br
          - when :op_return
            - if script.get_op_return_data
              Data: #{script.get_op_return_data}
            - else
              (No data)
          - if Bitcoin.namecoin? && script.is_namecoin?
            - name = txout.get_namecoin_name
            - if name.name
              #{link_to(name.name, name_path(name.name))}: #{name.value || name.hash}
            - else
              Hash: #{name.hash}
            %br
            - addr = txout.get_address
            = link_to(addr, address_path(addr))
          - if script.type == :unknown
            %span{class: "error"} Unknown script type
        %td
          %pre= script.to_string rescue "?"
        %td
          - if next_input
            = link_to "Run Script", script_path("#{next_input.get_tx.hash}:#{next_input.tx_idx}")

app/views/blocks/unconfirmed.html.haml
%table.list
  %tr
    %th Hash
    %th Inputs
    %th Outputs
    %th Size
    %th Value

  = render :partial => 'tx', :collection => @tx