config/routes.rb
BlockBrowser::Application.routes.draw do

  get 'blocks' => 'blocks#index', as: :blocks
  get 'block/:id' => 'blocks#show', as: :block
  get 'tx/:id' => 'tx#show', as: :tx
  get 'script/:id' => 'scripts#show', as: :script
  get 'script/:script_sig/:pk_script' => 'scripts#show'
  get 'script/:script_sig/:pk_script/:sig_hash' => 'scripts#show'
  get 'script' => 'scripts#show'
  get 'address/:id/unspent' => 'address#unspent', as: :address_unspent
  get 'address/:id' => 'address#show', as: :address

  get 'search/:search' => 'search#search'
  get 'search' => 'search#search', as: :search

  get 'unconfirmed' => 'blocks#unconfirmed', as: :unconfirmed
  get 'scripts/:type' => 'scripts#index', as: :scripts
  get 'p2sh_scripts/:type' => 'scripts#p2sh_index', as: :p2sh_scripts

  get 'relay_tx' => 'relay#relay_tx'
  post 'relay_tx' => 'relay#relay_tx'

  get 'api' => 'api#index', as: :api
  get 'api/block' => 'api#block', as: :block_api
  get 'api/tx' => 'api#tx', as: :tx_api
  get 'api/address' => 'api#address', as: :address_api
  get 'api/relay' => 'api#relay', as: :relay_api
  get 'api/stats' => 'api#stats', as: :stats_api
  get 'api/schema' => 'api#schema', as: :schema_api

  get 'graphs' => 'blocks#graphs', as: :graphs

  get 'about' => 'blocks#about', as: :about
  get 'stats' => 'stats#stats', as: :stats
  get 'source' => 'source#source', as: :source

  if Bitcoin.network_project == :namecoin
    get 'names' => 'names#index', as: :names
    get 'name/heights/*name' => 'names#heights', as: :name_heights
    get 'name/*name' => 'names#show', as: :name
    get 'api/name' => 'api#name', as: :name_api
  end

  root :to => 'blocks#index'

end

app/controllers/tx_controller.rb
class TxController < ApplicationController

  def show
    @tx = STORE.tx(params[:id])
    return render_error("Tx #{params[:id]} not found.", 404)  unless @tx
    @blk = STORE.db[:blk][id: @tx.blk_id, chain: 0]
    @blk ||= STORE.db[:blk][id: STORE.db[:blk_tx][tx_id: @tx.id][:blk_id]]

    respond_to do |format|
      format.html do
        @page_title = "Transaction Details"
      end
      format.json { render text: JSON.pretty_generate(tx_data(@tx, @blk)) }
      format.hex { render text: @tx.to_payload.hth }
      format.bin { render text: @tx.to_payload }
    end
  end

end

app/views/tx/show.html.haml
%table.details
  %tr
    %th Transaction
    %th= @tx.hash
  %tr
    %th Normalized Hash
    %td= @tx.nhash
  %tr
    %th Block
    %td
      - if @blk
        = link_to(@blk[:hash].hth, block_path(@blk[:hash].hth))
      - else
        unconfirmed
  %tr
    %th Confirmations
    %td
      - if @blk
        = STORE.height - @blk[:height] + 1
        (At Height: #{@blk[:height]})
        - unless @blk[:chain] == 0
          %span{style: "color:red"} (#{["Main", "Side", "Orphan"][@blk[:chain]]} Chain!)
      - else
        unconfirmed

  - cache("tx/#{@tx.hash}/details") do
    - if Bitcoin.namecoin?
      %tr
        %th Version
        %td= @tx.ver == 0x7100 ? "Namecoin" : "Bitcoin"
    %tr
      %th Size
      %td= @tx.to_payload.bytesize
    %tr
      %th Inputs
      %td= @tx.in.size
    %tr
      %th Outputs
      %td= @tx.out.size
    - if @tx.in.size == 1 && @tx.in[0].coinbase?
      - input_value = Bitcoin.block_creation_reward(@blk[:height])
    - else
      - input_value = @tx.in.map(&:get_prev_out).map(&:value).sum rescue '?'
    %tr
      %th Input Value
      %td= format_amount(input_value) rescue '?'
    - output_value = @tx.out.map(&:value).sum
    %tr
      %th Output Value
      %td= format_amount(output_value)
    %tr
      %th Fee
      %td= format_amount(input_value - output_value) rescue '?'
    - if @tx.lock_time != 0
      %tr
        %th Lock Time
        %td
          - if @tx.lock_time < 500_000_000
            - block = STORE.db[:blk][height: @tx.lock_time, chain: 0][:hash].hth
            Block #{link_to @tx.lock_time, "/block/#{block}"}
          - else
            #{@tx.lock_time} (#{format_time @tx.lock_time})
    %tr
      %th Formats
      %td
        = link_to "[json]", "/tx/#{@tx.hash}.json"
        = link_to "[hex]", "/tx/#{@tx.hash}.hex"
        = link_to "[binary]", "/tx/#{@tx.hash}.bin"

%h3 Inputs
%table.list
  %tr
    %th IDX
    %th Type
    %th Previous Output
    %th Value
    %th From Address
    %th Script
    - if display_sequence = @tx.in.map(&:sequence).any? {|s| s.unpack("I")[0] != 0xffffffff }
      %th Sequence
    %th Debug


  - @tx.in.each_with_index do |txin, idx|
    %tr{:class => cycle('odd', 'even')}
      - prev_out = txin.get_prev_out
      - cache("tx/#{@tx.hash}/in/#{idx}/#{!!prev_out}") do
        %td= idx
        - if txin.coinbase?
          %td generation
          %td none
          %td.value= format_amount(Bitcoin.block_creation_reward(@blk[:height]))
          %td -
          %td= txin.script_sig.unpack("H*")[0]
        - else
          - if prev_out
            %td
              = link_to(prev_out.type, "/scripts/#{prev_out.type}")
              - if prev_out.type == :script_hash
                %br/
                (#{link_to txin.p2sh_type, "/p2sh_scripts/#{txin.p2sh_type}"})
            %td
              = link_to(truncate(prev_out.get_tx.hash, :length => 16), tx_path(prev_out.get_tx.hash))
              = "/ #{txin.prev_out_index}"
            %td.value= format_amount(prev_out.value) rescue "?"
            - if prev_out.get_address
              %td
                - prev_out.get_addresses.each do |address|
                  = address_link(address)
                  %br
            - else
              %td not seen
            %td
              %pre
                = Bitcoin::Script.new(txin.script_sig).to_string.split(" ").join("\n")
            - if display_sequence
              %td= txin.sequence.unpack("I")[0].to_s(16)
            %td= link_to "Run Script", script_path("#{@tx.hash}:#{idx}")
          - else
            %td{:colspan => 5} not seen

%h3 Outputs
%table.list
  %tr
    %th IDX
    %th Type
    %th Next Input
    %th Value
    %th To Address
    %th Script
    %th Debug
  - @tx.out.each_with_index do |txout, idx|
    - next_input = STORE.db[:txin][prev_out: @tx.hash.htb.reverse.to_sequel_blob, prev_out_index: idx]
    %tr{:class => cycle('odd', 'even')}
      - cache("tx/#{@tx.hash}/out/#{idx}/#{!!next_input}") do
        - next_input = STORE.wrap_txin(next_input)
        - script = Bitcoin::Script.new(txout.pk_script) rescue nil
        %td= idx
        %td
          = link_to(txout.type, "/scripts/#{txout.type}")
          - if txout.type == :script_hash
            %br/
            - if next_in = txout.get_next_in
              (#{link_to next_in.p2sh_type, "/p2sh_scripts/#{next_input.p2sh_type}"})
            - else
              (unspent)
        %td
          - if next_input
            - tx_hash = next_input.get_tx.hash
            = link_to(truncate(tx_hash, :length => 16, :omission => '...'), tx_path(tx_hash))
            = "/ #{next_input.tx_idx}"
          - else
            not seen

        %td.value= format_amount(txout.value)
        %td
          - case script.type
          - when :pubkey, :pubkey_hash, :script_hash
            = address_link(txout.get_address)
          - when :multisig
            - addrs = script.get_multisig_addresses
            multisig (#{script.get_signatures_required} of #{script.get_keys_provided}):
            %br/
            - addrs.each do |address|
              = address_link(address)
              %br
          - when :op_return
            - if script.get_op_return_data
              Data: #{script.get_op_return_data}
            - else
              (No data)
          - if Bitcoin.namecoin? && script.is_namecoin?
            - name = txout.get_namecoin_name
            - if name.name
              #{link_to(name.name, name_path(name.name))}: #{name.value || name.hash}
            - else
              Hash: #{name.hash}
            %br
            = address_link(txout.get_address)
          - if script.type == :unknown
            %span{class: "error"} Unknown script type
        %td
          %pre= script.to_string rescue "?"
        %td
          - if next_input
            = link_to "Run Script", script_path("#{next_input.get_tx.hash}:#{next_input.tx_idx}")